# Site settings
title: Tom Paradise Portfolio
email: Tomparadise1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My portfolio.
baseurl: "/"
url: https://github.com/TomParadise/TomParadise.github.io.git
twitter_username: Tom_Para1
github_username:  TomParadise

# SASS directory
sass:
   sass_dir: ./_sass/
    
# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Build settings
markdown: kramdown
hightlighter: 'rouge' 

# Pagination
paginate: 5
paginate_path: "/home/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

